kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: flemington/aiopslab-kind:latest
    extraMounts:
      - hostPath: /mnt/datadrive/prometheus
        containerPath: /datadrive/prometheus
  - role: worker
    image: flemington/aiopslab-kind:latest
    extraMounts:
      - hostPath: /mnt/datadrive/prometheus
        containerPath: /datadrive/prometheus
